services:
  scraper:
    build: ./workshop-steam-scraper
    container_name: workshop-steam-scraper
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - ./scraped-data:/app/scraped-data
